const products = [
  {
    id: 1,
    name: "Anodized Panel Industrial Kit",
    price: "$79",
    image:
      "https://xtratheme.com/elementor/factory/wp-content/uploads/sites/8/2018/09/s10.jpg",

    images: [
      "https://xtratheme.com/elementor/factory/wp-content/uploads/sites/8/2018/09/s10.jpg",
      "https://xtratheme.com/elementor/factory/wp-content/uploads/sites/8/2018/09/s9.jpg",
      "https://xtratheme.com/elementor/factory/wp-content/uploads/sites/8/2018/09/1.jpg",
    ],
    category: "Uncategorized",
    SKU: "SKU_121",
    Status: 89,
    Tags: ["package", "premium", "pro"],
    Weight: 22,
    Dimensions: "25 × 44 × 38 cm",
    Product_year: 2024,
    Product_manual: "Included in the package",
    Refundable: "Up to 14 days",
  },
  {
    id: 2,
    name: "Electric Pallet Stacker",
    price: "$99",
    image:
      "https://xtratheme.com/elementor/factory/wp-content/uploads/sites/8/2018/09/s9.jpg",
    images: [
      "https://xtratheme.com/elementor/factory/wp-content/uploads/sites/8/2018/09/s10.jpg",
      "https://xtratheme.com/elementor/factory/wp-content/uploads/sites/8/2018/09/s9.jpg",
      "https://xtratheme.com/elementor/factory/wp-content/uploads/sites/8/2018/09/1.jpg",
    ],
    category: "Pro Products",
    SKU: "SKU_119",
    Status: 72,
    Tags: ["all", "one", "package", "pro"],
    Weight: 19,
    Dimensions: "50 × 49 × 46 cm",
    Product_year: 2024,
    Product_manual: "Included in the package",
    Refundable: "Up to 14 days",
  },
  {
    id: 3,
    name: "Gas Turbine v4",
    price: "$29",
    image:
      "https://xtratheme.com/elementor/factory/wp-content/uploads/sites/8/2018/09/1.jpg",
    images: [
      "https://xtratheme.com/elementor/factory/wp-content/uploads/sites/8/2018/09/s10.jpg",
      "https://xtratheme.com/elementor/factory/wp-content/uploads/sites/8/2018/09/s9.jpg",
      "https://xtratheme.com/elementor/factory/wp-content/uploads/sites/8/2018/09/1.jpg",
    ],
    category: "Pro Products",
    SKU: "SKU_43",
    Status: 98,
    Tags: ["package", "premium", "pro"],
    Weight: 11,
    Dimensions: "39 × 27 × 33 cm",
    Product_year: 2024,
    Product_manual: "Included in the package",
    Refundable: "Up to 14 days",
  },
  {
    id: 4,
    name: "Industrial Air Conditioner",
    price: "$69",
    image:
      "https://xtratheme.com/elementor/factory/wp-content/uploads/sites/8/2018/09/s5.jpg",
    images: [
      "https://xtratheme.com/elementor/factory/wp-content/uploads/sites/8/2018/09/s10.jpg",
      "https://xtratheme.com/elementor/factory/wp-content/uploads/sites/8/2018/09/s9.jpg",
      "https://xtratheme.com/elementor/factory/wp-content/uploads/sites/8/2018/09/1.jpg",
    ],
    category: "New Products",
    SKU: "SKU_105",
    Status: 72,
    Tags: ["new", "package", "special"],
    Weight: 10,
    Dimensions: "35 × 26 × 56 cm",
    Product_year: 2024,
    Product_manual: "Included in the package",
    Refundable: "Up to 14 days",
  },
  {
    id: 5,
    name: "Industrial Mechanical Modern Gear",
    price: "$39",
    image:
      "https://xtratheme.com/elementor/factory/wp-content/uploads/sites/8/2018/09/s2.jpg",
    category: "Ultimate",
    SKU: "SKU_96",
    Status: 112,
    Tags: ["premium", "package", "ultimate"],
    Weight: 15,
    Dimensions: "67 × 51 × 47 cm",
    Product_year: 2024,
    Product_manual: "Included in the package",
    Refundable: "Up to 14 days",
  },
  {
    id: 6,
    name: "Industrial Turbine XD5",
    price: "$44",
    image:
      "https://xtratheme.com/elementor/factory/wp-content/uploads/sites/8/2018/09/s3.jpg",
    images: [
      "https://xtratheme.com/elementor/factory/wp-content/uploads/sites/8/2018/09/s10.jpg",
      "https://xtratheme.com/elementor/factory/wp-content/uploads/sites/8/2018/09/s9.jpg",
      "https://xtratheme.com/elementor/factory/wp-content/uploads/sites/8/2018/09/1.jpg",
    ],
    category: "Pro Products",
    SKU: "SKU_99",
    Status: 73,
    Tags: ["personal", "package", "pro"],
    Weight: 5,
    Dimensions: "20 × 35 × 45 cm",
    Product_year: 2024,
    Product_manual: "Included in the package",
    Refundable: "Up to 14 days",
  },
  {
    id: 7,
    name: "Road Rollwe Pendant",
    price: "$47",
    image:
      "https://xtratheme.com/elementor/factory/wp-content/uploads/sites/8/2018/09/s6.jpg",
    images: [
      "https://xtratheme.com/elementor/factory/wp-content/uploads/sites/8/2018/09/s10.jpg",
      "https://xtratheme.com/elementor/factory/wp-content/uploads/sites/8/2018/09/s9.jpg",
      "https://xtratheme.com/elementor/factory/wp-content/uploads/sites/8/2018/09/1.jpg",
    ],
    category: "Ultimate",
    SKU: "SKU_108",
    Status: 110,
    Tags: ["premium", "package", "pro"],
    Weight: 32,
    Dimensions: "48 × 25 × 46 cm",
    Product_year: 2024,
    Product_manual: "Included in the package",
    Refundable: "Up to 14 days",
  },
  {
    id: 8,
    name: "Theodolite Spinner Modern",
    price: "$79",
    image:
      "https://xtratheme.com/elementor/factory/wp-content/uploads/sites/8/2018/09/s8.jpg",
    images: [
      "https://xtratheme.com/elementor/factory/wp-content/uploads/sites/8/2018/09/s10.jpg",
      "https://xtratheme.com/elementor/factory/wp-content/uploads/sites/8/2018/09/s9.jpg",
      "https://xtratheme.com/elementor/factory/wp-content/uploads/sites/8/2018/09/1.jpg",
    ],
    category: "UnCategorized",
    SKU: "SKU_115",
    Status: 88,
    Tags: ["bundle", "ultimate", "unlimited"],
    Weight: 24,
    Dimensions: "37 × 56 × 58 cm",
    Product_year: 2024,
    Product_manual: "Included in the package",
    Refundable: "Up to 14 days",
  },
];
export default products;
